-- MySQL Script generated by MySQL Workbench
-- Sat 06 Mar 2021 03:25:49 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EXPRESSFOOD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EXPRESSFOOD` ;

-- -----------------------------------------------------
-- Schema EXPRESSFOOD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EXPRESSFOOD` ;
USE `EXPRESSFOOD` ;

-- -----------------------------------------------------
-- Table `EXPRESSFOOD`.`compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EXPRESSFOOD`.`compte` ;

CREATE TABLE IF NOT EXISTS `EXPRESSFOOD`.`compte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `mdp` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(20) NOT NULL,
  `statut` VARCHAR(255) NULL,
  `position` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXPRESSFOOD`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EXPRESSFOOD`.`commande` ;

CREATE TABLE IF NOT EXISTS `EXPRESSFOOD`.`commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_creation` DATETIME NOT NULL,
  `date_paiement` DATETIME NULL,
  `date_livraison` DATETIME NULL,
  `statut_livraison` VARCHAR(255) NULL,
  `prix` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commande_compte1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_commande_compte1`
    FOREIGN KEY (`client_id`)
    REFERENCES `EXPRESSFOOD`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXPRESSFOOD`.`plat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EXPRESSFOOD`.`plat` ;

CREATE TABLE IF NOT EXISTS `EXPRESSFOOD`.`plat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `details` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `date_publication` DATETIME NOT NULL,
  `menu_du_jour` DATE NOT NULL,
  `prix` INT NOT NULL,
  `cuisinier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plat_compte1_idx` (`cuisinier_id` ASC) VISIBLE,
  CONSTRAINT `fk_plat_compte1`
    FOREIGN KEY (`cuisinier_id`)
    REFERENCES `EXPRESSFOOD`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXPRESSFOOD`.`adresse_commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EXPRESSFOOD`.`adresse_commande` ;

CREATE TABLE IF NOT EXISTS `EXPRESSFOOD`.`adresse_commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `cp` VARCHAR(255) NOT NULL,
  `pays` VARCHAR(255) NOT NULL,
  `info` VARCHAR(255) NULL,
  `commande_id` INT NOT NULL,
  PRIMARY KEY (`id`, `commande_id`),
  INDEX `fk_adresse_commande_commande1_idx` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `fk_adresse_commande_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `EXPRESSFOOD`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXPRESSFOOD`.`adresse_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EXPRESSFOOD`.`adresse_client` ;

CREATE TABLE IF NOT EXISTS `EXPRESSFOOD`.`adresse_client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `cp` VARCHAR(255) NOT NULL,
  `pays` VARCHAR(255) NOT NULL,
  `info` VARCHAR(255) NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adresse_client_compte_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_adresse_client_compte`
    FOREIGN KEY (`client_id`)
    REFERENCES `EXPRESSFOOD`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXPRESSFOOD`.`commande_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EXPRESSFOOD`.`commande_item` ;

CREATE TABLE IF NOT EXISTS `EXPRESSFOOD`.`commande_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plat_id` INT NOT NULL,
  `commande_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commande_item_plat1_idx` (`plat_id` ASC) VISIBLE,
  INDEX `fk_commande_item_commande1_idx` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `fk_commande_item_plat1`
    FOREIGN KEY (`plat_id`)
    REFERENCES `EXPRESSFOOD`.`plat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_item_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `EXPRESSFOOD`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXPRESSFOOD`.`barquette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EXPRESSFOOD`.`barquette` ;

CREATE TABLE IF NOT EXISTS `EXPRESSFOOD`.`barquette` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_conditionnement` DATETIME NOT NULL,
  `cuisinier_id` INT NOT NULL,
  `livreur_id` INT NULL,
  `plat_id` INT NOT NULL,
  `commande_item_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_barquette_compte1_idx` (`cuisinier_id` ASC) VISIBLE,
  INDEX `fk_barquette_compte2_idx` (`livreur_id` ASC) VISIBLE,
  INDEX `fk_barquette_plat1_idx` (`plat_id` ASC) VISIBLE,
  INDEX `fk_barquette_commande_item1_idx` (`commande_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_barquette_compte1`
    FOREIGN KEY (`cuisinier_id`)
    REFERENCES `EXPRESSFOOD`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barquette_compte2`
    FOREIGN KEY (`livreur_id`)
    REFERENCES `EXPRESSFOOD`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barquette_plat1`
    FOREIGN KEY (`plat_id`)
    REFERENCES `EXPRESSFOOD`.`plat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barquette_commande_item1`
    FOREIGN KEY (`commande_item_id`)
    REFERENCES `EXPRESSFOOD`.`commande_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `compte` (`id`, `type`, `nom`, `mdp`, `mail`, `tel`, `statut`, `position`)
VALUES
(NULL, 'cuisinier', 'Gusto', 'qsdaze', 'gusto@hotmail.fr', '0765845689', NULL, NULL),
(NULL, 'cuisinier', 'Paul', 'qsdaze1234856', 'paul@gmail.com', '0708090405', NULL, NULL),
(NULL, 'livreur', 'Valérie', 'qsd456qsd', 'vava@yahoo.com', '0704010455', 'free', NULL),
(NULL, 'livreur', 'Robert', 'qsdqsd', 'roro@hotmail.com', '0756988745', 'free', NULL),
(NULL, 'client', 'Marta', 'poiopip', 'marata@gmail.fr', '07123645679', NULL, NULL),
(NULL, 'client', 'Henri', '45sq45q', 'hh@live.fr', '07546852135', NULL, NULL);

INSERT INTO `adresse_client` (`id`, `client_id`, `adresse`, `ville`, `cp`, `pays`, `info`) 
VALUES
(NULL, '5', '54 rue Clerie', 'Paris', '75002', 'France', 'Au fond du couloire, porte jaune'), 
(NULL, '6', '4 rue de Paris', 'Paris', '75011', 'France', NULL),
(NULL, '6', '2 av. Ivry', 'Paris', '75013', 'France', 'interphone 12');



INSERT INTO `plat` (`id`, `cuisinier_id`, `nom`, `details`, `image`, `date_publication`,`menu_du_jour`, `prix`)
VALUES
(NULL, '1', 'Pâte carbo', 'Lardon, oignon, champignon...', 'asset/img/pate_carbo.jpg', '2021-02-19 14:43:03','2021-02-19', '124'), 
(NULL, '2', 'Soupe aux truffes', 'Truffes, oignon, ail...', 'asset/img/soupe_truffe.jpg', '2021-02-19 14:43:03', '2021-02-19','138'), 
(NULL, '1', 'Mousse au chocolat', 'Oeuf, chocolat noir...', 'asset/img/mousse_choco.jpg', '2021-02-19 14:43:03', '2021-02-19','72'),
(NULL, '2', 'riz au lait', 'Riz, lait, sucre...', 'asset/img/riz_au_lait.jpg', '2021-02-19 14:43:03', '2021-02-19','86'); 


INSERT INTO `barquette` (`id`, `cuisinier_id`, `plat_id`, `date_conditionnement`, `livreur_id`) 
VALUES 
(NULL, '1', '1', '2021-02-19 15:57:50', '3'),
(NULL, '2', '2', '2021-02-19 15:57:50', '3'), 
(NULL, '1', '3', '2021-02-19 15:35:41', '3'), 
(NULL, '2', '4', '2021-02-19 15:57:50', '3'),
(NULL, '1', '1', '2021-02-19 15:57:50', '3'),
(NULL, '2', '2', '2021-02-19 15:57:50', '3'), 
(NULL, '1', '3', '2021-02-19 15:35:41', '3'), 
(NULL, '2', '4', '2021-02-19 15:57:50', '3'),
(NULL, '1', '1', '2021-02-19 15:57:50', '4'),
(NULL, '2', '2', '2021-02-19 15:57:50', '4'), 
(NULL, '1', '3', '2021-02-19 15:35:41', '4'), 
(NULL, '2', '4', '2021-02-19 15:57:50', '4'),
(NULL, '1', '1', '2021-02-19 15:57:50', '4'),
(NULL, '2', '2', '2021-02-19 15:57:50', NULL), 
(NULL, '1', '3', '2021-02-19 15:35:41', NULL), 
(NULL, '2', '4', '2021-02-19 15:57:50', NULL),
(NULL, '1', '1', '2021-02-19 15:57:50', NULL),
(NULL, '2', '2', '2021-02-19 15:57:50', NULL), 
(NULL, '1', '3', '2021-02-19 15:35:41', NULL), 
(NULL, '2', '4', '2021-02-19 15:57:50', NULL),
(NULL, '1', '1', '2021-02-19 15:57:50', NULL),
(NULL, '2', '2', '2021-02-19 15:57:50', NULL), 
(NULL, '1', '3', '2021-02-19 15:35:41', NULL), 
(NULL, '2', '4', '2021-02-19 15:57:50', NULL)
;
