drop table if exists COMPTE;
drop table if exists CLIENT;
drop table if exists CUISINIER;
drop table if exists LIVREUR;
drop table if exists PLAT;
drop table if exists CLIENTADR;
drop table if exists COMMANDEADR;

CREATE TABLE COMPTE
(
idcompte INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
type VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENT 
(
idclient INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(255) NOT NULL,
mail VARCHAR(255) NOT NULL,
mdp VARCHAR(255) NOT NULL,
tel VARCHAR(255) NOT NULL,
FOREIGN KEY (idcompte) REFERENCES COMPTE (idcompte)
);

CREATE TABLE LIVREUR 
(
idclient INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(255) NOT NULL,
mail VARCHAR(255) NOT NULL,
mdp VARCHAR(255) NOT NULL,
tel VARCHAR(255) NOT NULL,
statu VARCHAR(255) NOT NULL,
position VARCHAR(255) NOT NULL,
nb_plat INT NOT NULL,
FOREIGN KEY (idcompte) REFERENCES COMPTE (idcompte)
);

CREATE TABLE CUISINE
(
id_cuisinier INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(255) NOT NULL,
mail VARCHAR(255) NOT NULL,
mdp VARCHAR(255) NOT NULL,
tel VARCHAR(255) NOT NULL,
FOREIGN KEY (idcompte) REFERENCES COMTPE (idcompte)
);
